DELETE FROM CALIFICACIONENTITY;
DELETE FROM PROPUESTAENTITY;
DELETE FROM PAGOSENTITY;
DELETE FROM INVITACIONENTITY;
DELETE FROM TARJETADECREDITOENTITY;
DELETE FROM SOLICITUDENTITY;
DELETE FROM DOCUMENTOENTITY;
DELETE FROM CLIENTEENTITY;
DELETE FROM EMPLEADOENTITY;
DELETE FROM AREACONOCIMIENTOENTITY;
DELETE FROM IDIOMAENTITY;

insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (1, 'Marsiella', 'msawl0', 'mbubbins0@t-online.de', '6759681591832674427', 'eXNpt4bd', 1);
insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (2, 'Wendeline', 'wlukacs1', 'wcoxwell1@eventbrite.com', '6393087959654541', 'K6FC94qGO57v', 1);
insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (3, 'Rana', 'rwhitmore2', 'rcarse2@unesco.org', '3548139892709113', 'KSaUGAqS', 1);
insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (4, 'Pepito', 'pbucke3', 'pmitkin3@yandex.ru', '3533602473948621', 'vkTdydwTY3', 0);
insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (5, 'Waylan', 'wcaulcutt4', 'wzanini4@51.la', '67090721269707668', 'vC7MQg7V', 1);
insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (6, 'Ranique', 'rpendered5', 'rcorran5@europa.eu', '3552542365987756', 'yphK61E8eB', 0);
insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (7, 'Hortensia', 'hrulf6', 'hannear6@w3.org', '4017955629480', 'y75E6330pf', 0);
insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (8, 'Darren', 'dmaccumeskey7', 'dchamp7@opera.com', '6395199136488046', 'hHZ6QM', 1);
insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (9, 'Daffie', 'ddunican8', 'dcolum8@google.nl', '4041595527814562', 'wv68eic', 1);
insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (10, 'Mord', 'mgeleman9', 'mosgodby9@timesonline.co.uk', '4844302170453635', 'jD55kpfxxA5x', 1);
insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (11, 'Keir', 'keptona', 'kbrignella@mapquest.com', '5020721979124332', 'A0vVM6Tnw', 1);
insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (12, 'Shauna', 'shappertb', 'sruggb@ovh.net', '343663225257477', '8VF5ve', 1);
insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (13, 'Dagmar', 'dwalterc', 'dvlachc@huffingtonpost.com', '5002352710916604', '8asqRQiYe', 1);
insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (14, 'Jessamine', 'jsisnettd', 'jtreagustd@com.com', '3558061136070820', 'TMmJ2Ljqy', 0);
insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (15, 'Arlena', 'aclurowe', 'asore@simplemachines.org', '3569812522325385', 'JOu16cBMBrWg', 1);
insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (16, 'Richy', 'rbadlandf', 'rpenrithf@gov.uk', '343838035010866', 'ct1vdTgD7nn', 1);
insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (17, 'Reynold', 'rmartelg', 'rgehrtsg@i2i.jp', '5048377196337872', 'm50NTYyp', 0);
insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (18, 'Emlen', 'emcwhinneyh', 'eheningamh@dmoz.org', '3558890608418392', 'prT335', 1);
insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (19, 'Lammond', 'lgilleasei', 'lfayteri@so-net.ne.jp', '3528593608114451', 'qF0K5gA2GuA', 1);
insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (20, 'Brunhilda', 'breekiej', 'broukej@webmd.com', '3554946426783120', 'HELIJG2iao', 0);
insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (21, 'Juana', 'jsoigouxk', 'jalwellk@dailymotion.com', '372301953268697', 'UouDEK7', 0);
insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (22, 'Jana', 'jdonahol', 'jelnorl@linkedin.com', '3529978623236950', '0xBIIWjOni', 1);
insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (23, 'Tobe', 'teglingtonm', 'tboamem@meetup.com', '5294810515484083', 'IdDg3Zl', 0);
insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (24, 'Augustus', 'alateyn', 'acolbournen@unesco.org', '3568827927430938', 'QCiKpIrpcx', 1);
insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (25, 'Harwilll', 'hnearso', 'hbaxandallo@ycombinator.com', '30363077527519', 'fiWSU0N', 0);
insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (26, 'Waverley', 'wfoardp', 'wpollastrop@tripod.com', '5519323547804533', 'X33BChA', 1);
insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (27, 'Vally', 'valbroq', 'vhindsbergq@wsj.com', '5018101552071360460', 'IEMC8FWN5j', 0);
insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (28, 'Nikaniki', 'nlegallor', 'nlaylandr@biblegateway.com', '3542632387158495', '9vBMdqvoKz5', 1);
insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (29, 'Brewer', 'bgermons', 'brotterys@amazonaws.com', '3568059324493091', 'MO7gLV29Q', 1);
insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (30, 'Pietra', 'ppriddist', 'pnelmest@blog.com', '374622457259256', 'faTrYwUP', 0);

insert into TARJETADECREDITOENTITY (ID, NUMEROTARJETACREDITO, CCV, MESEXPIRACION, ANIOEXPIRACION, REDBANCARIA, NOMBRETITULAR, CLIENTE_ID) values (1, 6636872626612966, 863, 6, 2027, 'jcb', 'Cecelia Grouse', 15);
insert into TARJETADECREDITOENTITY (ID, NUMEROTARJETACREDITO, CCV, MESEXPIRACION, ANIOEXPIRACION, REDBANCARIA, NOMBRETITULAR, CLIENTE_ID) values (2, 1668000783657661, 951, 7, 2021, 'maestro', 'Brig Bummfrey', 5);
insert into TARJETADECREDITOENTITY (ID, NUMEROTARJETACREDITO, CCV, MESEXPIRACION, ANIOEXPIRACION, REDBANCARIA, NOMBRETITULAR, CLIENTE_ID) values (3, 5806752978767257, 240, 12, 2023, 'maestro', 'Garrott Fullilove', 5);
insert into TARJETADECREDITOENTITY (ID, NUMEROTARJETACREDITO, CCV, MESEXPIRACION, ANIOEXPIRACION, REDBANCARIA, NOMBRETITULAR, CLIENTE_ID) values (4, 2946998027093699, 881, 11, 2021, 'americanexpress', 'Ramon Munro', 2);
insert into TARJETADECREDITOENTITY (ID, NUMEROTARJETACREDITO, CCV, MESEXPIRACION, ANIOEXPIRACION, REDBANCARIA, NOMBRETITULAR, CLIENTE_ID) values (5, 3340744941436212, 314, 5, 2029, 'jcb', 'Jehanna Fairfoot', 30);
insert into TARJETADECREDITOENTITY (ID, NUMEROTARJETACREDITO, CCV, MESEXPIRACION, ANIOEXPIRACION, REDBANCARIA, NOMBRETITULAR, CLIENTE_ID) values (6, 6190756412962343, 552, 10, 2027, 'jcb', 'Garrek Asquez', 7);
insert into TARJETADECREDITOENTITY (ID, NUMEROTARJETACREDITO, CCV, MESEXPIRACION, ANIOEXPIRACION, REDBANCARIA, NOMBRETITULAR, CLIENTE_ID) values (7, 5134915324382872, 590, 1, 2029, 'visa', 'Kariotta Ferson', 26);
insert into TARJETADECREDITOENTITY (ID, NUMEROTARJETACREDITO, CCV, MESEXPIRACION, ANIOEXPIRACION, REDBANCARIA, NOMBRETITULAR, CLIENTE_ID) values (8, 5013820993508469, 890, 8, 2029, 'jcb', 'Arda Beek', 27);
insert into TARJETADECREDITOENTITY (ID, NUMEROTARJETACREDITO, CCV, MESEXPIRACION, ANIOEXPIRACION, REDBANCARIA, NOMBRETITULAR, CLIENTE_ID) values (9, 6829018778297358, 858, 2, 2023, 'jcb', 'Glynnis Neilus', 21);
insert into TARJETADECREDITOENTITY (ID, NUMEROTARJETACREDITO, CCV, MESEXPIRACION, ANIOEXPIRACION, REDBANCARIA, NOMBRETITULAR, CLIENTE_ID) values (10, 4919181294123263, 956, 4, 2019, 'diners-club-carte-blanche', 'Warden Grishunin', 12);
insert into TARJETADECREDITOENTITY (ID, NUMEROTARJETACREDITO, CCV, MESEXPIRACION, ANIOEXPIRACION, REDBANCARIA, NOMBRETITULAR, CLIENTE_ID) values (11, 3867451084345727, 675, 8, 2027, 'americanexpress', 'Mart Olanda', 5);
insert into TARJETADECREDITOENTITY (ID, NUMEROTARJETACREDITO, CCV, MESEXPIRACION, ANIOEXPIRACION, REDBANCARIA, NOMBRETITULAR, CLIENTE_ID) values (12, 5000300971476768, 203, 9, 2024, 'maestro', 'Rhea Djuricic', 28);
insert into TARJETADECREDITOENTITY (ID, NUMEROTARJETACREDITO, CCV, MESEXPIRACION, ANIOEXPIRACION, REDBANCARIA, NOMBRETITULAR, CLIENTE_ID) values (13, 4048111799635815, 123, 9, 2026, 'visa-electron', 'Marleah Skilbeck', 12);
insert into TARJETADECREDITOENTITY (ID, NUMEROTARJETACREDITO, CCV, MESEXPIRACION, ANIOEXPIRACION, REDBANCARIA, NOMBRETITULAR, CLIENTE_ID) values (14, 1528325293107859, 552, 9, 2027, 'jcb', 'Marcelline Whiting', 1);
insert into TARJETADECREDITOENTITY (ID, NUMEROTARJETACREDITO, CCV, MESEXPIRACION, ANIOEXPIRACION, REDBANCARIA, NOMBRETITULAR, CLIENTE_ID) values (15, 6600603542208228, 712, 7, 2024, 'visa-electron', 'Maddalena Maxted', 21);
insert into TARJETADECREDITOENTITY (ID, NUMEROTARJETACREDITO, CCV, MESEXPIRACION, ANIOEXPIRACION, REDBANCARIA, NOMBRETITULAR, CLIENTE_ID) values (16, 7582592402110220, 356, 1, 2023, 'switch', 'Wilow Cathery', 29);
insert into TARJETADECREDITOENTITY (ID, NUMEROTARJETACREDITO, CCV, MESEXPIRACION, ANIOEXPIRACION, REDBANCARIA, NOMBRETITULAR, CLIENTE_ID) values (17, 3328846983146646, 892, 4, 2028, 'jcb', 'Sansone Elen', 12);
insert into TARJETADECREDITOENTITY (ID, NUMEROTARJETACREDITO, CCV, MESEXPIRACION, ANIOEXPIRACION, REDBANCARIA, NOMBRETITULAR, CLIENTE_ID) values (18, 9688014453321907, 144, 2, 2029, 'bankcard', 'Druci Schoffler', 20);
insert into TARJETADECREDITOENTITY (ID, NUMEROTARJETACREDITO, CCV, MESEXPIRACION, ANIOEXPIRACION, REDBANCARIA, NOMBRETITULAR, CLIENTE_ID) values (19, 7778665661870397, 483, 5, 2029, 'jcb', 'Nina Greste', 14);
insert into TARJETADECREDITOENTITY (ID, NUMEROTARJETACREDITO, CCV, MESEXPIRACION, ANIOEXPIRACION, REDBANCARIA, NOMBRETITULAR, CLIENTE_ID) values (20, 9424804251887448, 614, 8, 2028, 'switch', 'Deonne Dilke', 11);
insert into TARJETADECREDITOENTITY (ID, NUMEROTARJETACREDITO, CCV, MESEXPIRACION, ANIOEXPIRACION, REDBANCARIA, NOMBRETITULAR, CLIENTE_ID) values (21, 1032869624835113, 899, 9, 2027, 'diners-club-carte-blanche', 'Katusha Jancic', 14);
insert into TARJETADECREDITOENTITY (ID, NUMEROTARJETACREDITO, CCV, MESEXPIRACION, ANIOEXPIRACION, REDBANCARIA, NOMBRETITULAR, CLIENTE_ID) values (22, 9526981233041852, 644, 3, 2029, 'diners-club-carte-blanche', 'Vite de Wilde', 23);
insert into TARJETADECREDITOENTITY (ID, NUMEROTARJETACREDITO, CCV, MESEXPIRACION, ANIOEXPIRACION, REDBANCARIA, NOMBRETITULAR, CLIENTE_ID) values (23, 4959070162447964, 793, 9, 2021, 'jcb', 'Mahmud Sollner', 21);
insert into TARJETADECREDITOENTITY (ID, NUMEROTARJETACREDITO, CCV, MESEXPIRACION, ANIOEXPIRACION, REDBANCARIA, NOMBRETITULAR, CLIENTE_ID) values (24, 9012902168848613, 992, 3, 2026, 'bankcard', 'Johnath Foffano', 17);
insert into TARJETADECREDITOENTITY (ID, NUMEROTARJETACREDITO, CCV, MESEXPIRACION, ANIOEXPIRACION, REDBANCARIA, NOMBRETITULAR, CLIENTE_ID) values (25, 7271141994013901, 895, 5, 2029, 'americanexpress', 'Nickolai Cuardall', 5);
insert into TARJETADECREDITOENTITY (ID, NUMEROTARJETACREDITO, CCV, MESEXPIRACION, ANIOEXPIRACION, REDBANCARIA, NOMBRETITULAR, CLIENTE_ID) values (26, 7675091061037665, 708, 3, 2019, 'china-unionpay', 'Quinlan Twelve', 30);
insert into TARJETADECREDITOENTITY (ID, NUMEROTARJETACREDITO, CCV, MESEXPIRACION, ANIOEXPIRACION, REDBANCARIA, NOMBRETITULAR, CLIENTE_ID) values (27, 2340315391762221, 815, 11, 2020, 'maestro', 'Olga Hakonsson', 28);
insert into TARJETADECREDITOENTITY (ID, NUMEROTARJETACREDITO, CCV, MESEXPIRACION, ANIOEXPIRACION, REDBANCARIA, NOMBRETITULAR, CLIENTE_ID) values (28, 2059974546396189, 212, 7, 2023, 'diners-club-carte-blanche', 'Ashly Issit', 18);
insert into TARJETADECREDITOENTITY (ID, NUMEROTARJETACREDITO, CCV, MESEXPIRACION, ANIOEXPIRACION, REDBANCARIA, NOMBRETITULAR, CLIENTE_ID) values (29, 6564508174192900, 385, 4, 2020, 'visa-electron', 'Jenni Lynthal', 3);
insert into TARJETADECREDITOENTITY (ID, NUMEROTARJETACREDITO, CCV, MESEXPIRACION, ANIOEXPIRACION, REDBANCARIA, NOMBRETITULAR, CLIENTE_ID) values (30, 3741876050742290, 278, 10, 2020, 'switch', 'Marna Warden', 25);

-- insert into PAGOSENTITY (ID, PAGOAPROBADO, CLIENTE_ID, PROPUESTA_ID) values (1, 0, 16, 1);
-- insert into PAGOSENTITY (ID, PAGOAPROBADO, CLIENTE_ID, PROPUESTA_ID) values (2, 1, 20, 2);
-- insert into PAGOSENTITY (ID, PAGOAPROBADO, CLIENTE_ID, PROPUESTA_ID) values (3, 1, 6, 3);
-- insert into PAGOSENTITY (ID, PAGOAPROBADO, CLIENTE_ID, PROPUESTA_ID) values (4, 0, 24, 4);
-- insert into PAGOSENTITY (ID, PAGOAPROBADO, CLIENTE_ID, PROPUESTA_ID) values (5, 1, 25, 5);
-- insert into PAGOSENTITY (ID, PAGOAPROBADO, CLIENTE_ID, PROPUESTA_ID) values (6, 1, 30, 6);
-- insert into PAGOSENTITY (ID, PAGOAPROBADO, CLIENTE_ID, PROPUESTA_ID) values (7, 0, 20, 7);
-- insert into PAGOSENTITY (ID, PAGOAPROBADO, CLIENTE_ID, PROPUESTA_ID) values (8, 0, 15, 8);
-- insert into PAGOSENTITY (ID, PAGOAPROBADO, CLIENTE_ID, PROPUESTA_ID) values (9, 1, 13, 9);
-- insert into PAGOSENTITY (ID, PAGOAPROBADO, CLIENTE_ID, PROPUESTA_ID) values (10, 1, 2, 10);
-- insert into PAGOSENTITY (ID, PAGOAPROBADO, CLIENTE_ID, PROPUESTA_ID) values (11, 0, 25, 11);
-- insert into PAGOSENTITY (ID, PAGOAPROBADO, CLIENTE_ID, PROPUESTA_ID) values (12, 0, 25, 12);
-- insert into PAGOSENTITY (ID, PAGOAPROBADO, CLIENTE_ID, PROPUESTA_ID) values (13, 1, 19, 13);
-- insert into PAGOSENTITY (ID, PAGOAPROBADO, CLIENTE_ID, PROPUESTA_ID) values (14, 1, 3, 14);
-- insert into PAGOSENTITY (ID, PAGOAPROBADO, CLIENTE_ID, PROPUESTA_ID) values (15, 0, 20, 15);
-- insert into PAGOSENTITY (ID, PAGOAPROBADO, CLIENTE_ID, PROPUESTA_ID) values (16, 1, 8, 16);
-- insert into PAGOSENTITY (ID, PAGOAPROBADO, CLIENTE_ID, PROPUESTA_ID) values (17, 0, 7, 17);
-- insert into PAGOSENTITY (ID, PAGOAPROBADO, CLIENTE_ID, PROPUESTA_ID) values (18, 1, 25, 18);
-- insert into PAGOSENTITY (ID, PAGOAPROBADO, CLIENTE_ID, PROPUESTA_ID) values (19, 0, 21, 19);
-- insert into PAGOSENTITY (ID, PAGOAPROBADO, CLIENTE_ID, PROPUESTA_ID) values (20, 1, 5, 20);
-- insert into PAGOSENTITY (ID, PAGOAPROBADO, CLIENTE_ID, PROPUESTA_ID) values (21, 1, 14, 21);
-- insert into PAGOSENTITY (ID, PAGOAPROBADO, CLIENTE_ID, PROPUESTA_ID) values (22, 1, 8, 22);
-- insert into PAGOSENTITY (ID, PAGOAPROBADO, CLIENTE_ID, PROPUESTA_ID) values (23, 0, 15, 23);
-- insert into PAGOSENTITY (ID, PAGOAPROBADO, CLIENTE_ID, PROPUESTA_ID) values (24, 0, 21, 24);
-- insert into PAGOSENTITY (ID, PAGOAPROBADO, CLIENTE_ID, PROPUESTA_ID) values (25, 1, 5, 25);
-- insert into PAGOSENTITY (ID, PAGOAPROBADO, CLIENTE_ID, PROPUESTA_ID) values (26, 0, 11, 26);
-- insert into PAGOSENTITY (ID, PAGOAPROBADO, CLIENTE_ID, PROPUESTA_ID) values (27, 1, 27, 27);
-- insert into PAGOSENTITY (ID, PAGOAPROBADO, CLIENTE_ID, PROPUESTA_ID) values (28, 1, 30, 28);
-- insert into PAGOSENTITY (ID, PAGOAPROBADO, CLIENTE_ID, PROPUESTA_ID) values (29, 0, 5, 29);
-- insert into PAGOSENTITY (ID, PAGOAPROBADO, CLIENTE_ID, PROPUESTA_ID) values (30, 0, 24, 30);

insert into EMPLEADOENTITY (id, nombreEmpleado, correoElectronico, aniosExperiencia, nombreUsuario, contrasenia, trayectoria) values (1, 'Rodd', 'rraffeorty0@google.com.hk', 1, 'rsirmond0', '6xM5j4', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.');
insert into EMPLEADOENTITY (id, nombreEmpleado, correoElectronico, aniosExperiencia, nombreUsuario, contrasenia, trayectoria) values (2, 'Kristine', 'ksuarez1@ocn.ne.jp', 2, 'kliquorish1', 'GQZsE69', 'Etiam pretium iaculis justo. In hac habitasse platea dictumst.');
insert into EMPLEADOENTITY (id, nombreEmpleado, correoElectronico, aniosExperiencia, nombreUsuario, contrasenia, trayectoria) values (3, 'Lew', 'ljohanchon2@engadget.com', 3, 'lvial2', '07fbPGgPyYG', 'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
insert into EMPLEADOENTITY (id, nombreEmpleado, correoElectronico, aniosExperiencia, nombreUsuario, contrasenia, trayectoria) values (4, 'Harmonie', 'hchaperlin3@friendfeed.com', 4, 'hjobe3', 'a8LgzWLRlwQ', 'Aliquam sit amet diam in magna bibendum imperdiet.');
insert into EMPLEADOENTITY (id, nombreEmpleado, correoElectronico, aniosExperiencia, nombreUsuario, contrasenia, trayectoria) values (5, 'Adina', 'amedwell4@sourceforge.net', 5, 'aashbridge4', 'vuiqV0', 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.');
insert into EMPLEADOENTITY (id, nombreEmpleado, correoElectronico, aniosExperiencia, nombreUsuario, contrasenia, trayectoria) values (6, 'Arlena', 'ablasius5@imageshack.us', 6, 'aciotti5', 'sUCNEoZ', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.');
insert into EMPLEADOENTITY (id, nombreEmpleado, correoElectronico, aniosExperiencia, nombreUsuario, contrasenia, trayectoria) values (7, 'Amabelle', 'aseed6@blinklist.com', 7, 'aswabey6', 'bzcAAHqr65R', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into EMPLEADOENTITY (id, nombreEmpleado, correoElectronico, aniosExperiencia, nombreUsuario, contrasenia, trayectoria) values (8, 'Starla', 'sdurrans7@illinois.edu', 8, 'sseamons7', 'gpj7614gJYHB', 'Maecenas pulvinar lobortis est. Phasellus sit amet erat.');
insert into EMPLEADOENTITY (id, nombreEmpleado, correoElectronico, aniosExperiencia, nombreUsuario, contrasenia, trayectoria) values (9, 'Phylys', 'ptout8@vkontakte.ru', 9, 'plidgerton8', 'J6oBWfL3D0d', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.');
insert into EMPLEADOENTITY (id, nombreEmpleado, correoElectronico, aniosExperiencia, nombreUsuario, contrasenia, trayectoria) values (10, 'Denise', 'dpiddletown9@yahoo.com', 10, 'dpennini9', '7HPsQTA6', 'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.');
insert into EMPLEADOENTITY (id, nombreEmpleado, correoElectronico, aniosExperiencia, nombreUsuario, contrasenia, trayectoria) values (11, 'Lawrence', 'lpothburya@samsung.com', 11, 'lbransdena', 'R3ymWB', 'Vivamus in felis eu sapien cursus vestibulum.');
insert into EMPLEADOENTITY (id, nombreEmpleado, correoElectronico, aniosExperiencia, nombreUsuario, contrasenia, trayectoria) values (12, 'Dodie', 'dcucuzzab@sfgate.com', 12, 'ddonaghyb', 'odynYe1cNM', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.');
insert into EMPLEADOENTITY (id, nombreEmpleado, correoElectronico, aniosExperiencia, nombreUsuario, contrasenia, trayectoria) values (13, 'Bernadette', 'bkornesc@xrea.com', 13, 'bdodmanc', 'qIJ2uPfyi', 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.');
insert into EMPLEADOENTITY (id, nombreEmpleado, correoElectronico, aniosExperiencia, nombreUsuario, contrasenia, trayectoria) values (14, 'Margarethe', 'mmacmanusd@google.ru', 14, 'mcheasmand', 'kjub3gdo', 'Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
insert into EMPLEADOENTITY (id, nombreEmpleado, correoElectronico, aniosExperiencia, nombreUsuario, contrasenia, trayectoria) values (15, 'Efrem', 'erudgerde@foxnews.com', 15, 'ecolthurste', '9D8Y2ig', 'Donec ut dolor.');
insert into EMPLEADOENTITY (id, nombreEmpleado, correoElectronico, aniosExperiencia, nombreUsuario, contrasenia, trayectoria) values (16, 'Teodoor', 'tmabbettf@aboutads.info', 16, 'tjenckenf', 'MRJQzxzADhgs', 'Nulla tellus. In sagittis dui vel nisl.');
insert into EMPLEADOENTITY (id, nombreEmpleado, correoElectronico, aniosExperiencia, nombreUsuario, contrasenia, trayectoria) values (17, 'Rhona', 'rcamachog@facebook.com', 17, 'rchannong', 'Ns1H74UJ81', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna.');
insert into EMPLEADOENTITY (id, nombreEmpleado, correoElectronico, aniosExperiencia, nombreUsuario, contrasenia, trayectoria) values (18, 'Orville', 'oklimkovh@cnn.com', 18, 'opoolyh', 'y8Si1jiRhO6', 'Cras in purus eu magna vulputate luctus.');
insert into EMPLEADOENTITY (id, nombreEmpleado, correoElectronico, aniosExperiencia, nombreUsuario, contrasenia, trayectoria) values (19, 'Nadiya', 'npordalli@google.es', 19, 'nmarineri', '0KPDFO9kW', 'Nunc rhoncus dui vel sem.');
insert into EMPLEADOENTITY (id, nombreEmpleado, correoElectronico, aniosExperiencia, nombreUsuario, contrasenia, trayectoria) values (20, 'Tamma', 'tguielj@ifeng.com', 20, 'tnewcomj', '04YcNJ', 'Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.');
insert into EMPLEADOENTITY (id, nombreEmpleado, correoElectronico, aniosExperiencia, nombreUsuario, contrasenia, trayectoria) values (21, 'Yetty', 'ygarmansonk@newyorker.com', 21, 'ybeddiek', 'tIHimf8kmYZ', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into EMPLEADOENTITY (id, nombreEmpleado, correoElectronico, aniosExperiencia, nombreUsuario, contrasenia, trayectoria) values (22, 'Chickie', 'cofallonl@examiner.com', 22, 'ccarseyl', 'Ris14Fgi1Eb', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.');
insert into EMPLEADOENTITY (id, nombreEmpleado, correoElectronico, aniosExperiencia, nombreUsuario, contrasenia, trayectoria) values (23, 'Ludwig', 'lkickm@oracle.com', 23, 'ldalemanm', 'Dgo2MZZyKLp0', 'Vestibulum sed magna at nunc commodo placerat.');
insert into EMPLEADOENTITY (id, nombreEmpleado, correoElectronico, aniosExperiencia, nombreUsuario, contrasenia, trayectoria) values (24, 'Meghann', 'mgoodgen@amazonaws.com', 24, 'mcarahn', 'RonAy4', 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.');
insert into EMPLEADOENTITY (id, nombreEmpleado, correoElectronico, aniosExperiencia, nombreUsuario, contrasenia, trayectoria) values (25, 'Guenna', 'gdeliao@va.gov', 25, 'gcowderyo', 'ihHuoRRjJ', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into EMPLEADOENTITY (id, nombreEmpleado, correoElectronico, aniosExperiencia, nombreUsuario, contrasenia, trayectoria) values (26, 'Farica', 'fmibournep@cam.ac.uk', 26, 'fjerromep', '4SUlZzUtR0Y', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.');
insert into EMPLEADOENTITY (id, nombreEmpleado, correoElectronico, aniosExperiencia, nombreUsuario, contrasenia, trayectoria) values (27, 'Octavia', 'ostaplefordq@earthlink.net', 27, 'ocoveneyq', 'Qk7Lc3', 'Curabitur gravida nisi at nibh.');
insert into EMPLEADOENTITY (id, nombreEmpleado, correoElectronico, aniosExperiencia, nombreUsuario, contrasenia, trayectoria) values (28, 'Von', 'vmeadleyr@wikipedia.org', 28, 'vstothartr', 'mlqEcK0vNEb', 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into EMPLEADOENTITY (id, nombreEmpleado, correoElectronico, aniosExperiencia, nombreUsuario, contrasenia, trayectoria) values (29, 'Allianora', 'abeardsalls@ifeng.com', 29, 'amccuiss', 'wzm9CpTnIJq', 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.');
insert into EMPLEADOENTITY (id, nombreEmpleado, correoElectronico, aniosExperiencia, nombreUsuario, contrasenia, trayectoria) values (30, 'Shandeigh', 'shalversent@ed.gov', 30, 'sogust', 'EyN4ygkOO', 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.');
