DELETE FROM CALIFICACIONENTITY;
DELETE FROM PROPUESTAENTITY;
DELETE FROM PAGOSENTITY;
DELETE FROM INVITACIONENTITY;
DELETE FROM TARJETADECREDITOENTITY;
DELETE FROM SOLICITUDENTITY;
DELETE FROM DOCUMENTOENTITY;
DELETE FROM CLIENTEENTITY;
DELETE FROM EMPLEADOENTITY;
DELETE FROM AREACONOCIMIENTOENTITY;
DELETE FROM IDIOMAENTITY;

insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (1, 'Marsiella', 'msawl0', 'mbubbins0@t-online.de', '6759681591832674427', 'eXNpt4bd', 1);
insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (2, 'Wendeline', 'wlukacs1', 'wcoxwell1@eventbrite.com', '6393087959654541', 'K6FC94qGO57v', 1);
-- insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (3, 'Rana', 'rwhitmore2', 'rcarse2@unesco.org', '3548139892709113', 'KSaUGAqS', 1);
-- insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (4, 'Pepito', 'pbucke3', 'pmitkin3@yandex.ru', '3533602473948621', 'vkTdydwTY3', 0);
-- insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (5, 'Waylan', 'wcaulcutt4', 'wzanini4@51.la', '67090721269707668', 'vC7MQg7V', 1);
-- insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (6, 'Ranique', 'rpendered5', 'rcorran5@europa.eu', '3552542365987756', 'yphK61E8eB', 0);
-- insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (7, 'Hortensia', 'hrulf6', 'hannear6@w3.org', '4017955629480', 'y75E6330pf', 0);
-- insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (8, 'Darren', 'dmaccumeskey7', 'dchamp7@opera.com', '6395199136488046', 'hHZ6QM', 1);
-- insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (9, 'Daffie', 'ddunican8', 'dcolum8@google.nl', '4041595527814562', 'wv68eic', 1);
-- insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (10, 'Mord', 'mgeleman9', 'mosgodby9@timesonline.co.uk', '4844302170453635', 'jD55kpfxxA5x', 1);
-- insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (11, 'Keir', 'keptona', 'kbrignella@mapquest.com', '5020721979124332', 'A0vVM6Tnw', 1);
-- insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (12, 'Shauna', 'shappertb', 'sruggb@ovh.net', '343663225257477', '8VF5ve', 1);
-- insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (13, 'Dagmar', 'dwalterc', 'dvlachc@huffingtonpost.com', '5002352710916604', '8asqRQiYe', 1);
-- insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (14, 'Jessamine', 'jsisnettd', 'jtreagustd@com.com', '3558061136070820', 'TMmJ2Ljqy', 0);
-- insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (15, 'Arlena', 'aclurowe', 'asore@simplemachines.org', '3569812522325385', 'JOu16cBMBrWg', 1);
-- insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (16, 'Richy', 'rbadlandf', 'rpenrithf@gov.uk', '343838035010866', 'ct1vdTgD7nn', 1);
-- insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (17, 'Reynold', 'rmartelg', 'rgehrtsg@i2i.jp', '5048377196337872', 'm50NTYyp', 0);
-- insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (18, 'Emlen', 'emcwhinneyh', 'eheningamh@dmoz.org', '3558890608418392', 'prT335', 1);
-- insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (19, 'Lammond', 'lgilleasei', 'lfayteri@so-net.ne.jp', '3528593608114451', 'qF0K5gA2GuA', 1);
-- insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (20, 'Brunhilda', 'breekiej', 'broukej@webmd.com', '3554946426783120', 'HELIJG2iao', 0);
-- insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (21, 'Juana', 'jsoigouxk', 'jalwellk@dailymotion.com', '372301953268697', 'UouDEK7', 0);
-- insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (22, 'Jana', 'jdonahol', 'jelnorl@linkedin.com', '3529978623236950', '0xBIIWjOni', 1);
-- insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (23, 'Tobe', 'teglingtonm', 'tboamem@meetup.com', '5294810515484083', 'IdDg3Zl', 0);
-- insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (24, 'Augustus', 'alateyn', 'acolbournen@unesco.org', '3568827927430938', 'QCiKpIrpcx', 1);
-- insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (25, 'Harwilll', 'hnearso', 'hbaxandallo@ycombinator.com', '30363077527519', 'fiWSU0N', 0);
-- insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (26, 'Waverley', 'wfoardp', 'wpollastrop@tripod.com', '5519323547804533', 'X33BChA', 1);
-- insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (27, 'Vally', 'valbroq', 'vhindsbergq@wsj.com', '5018101552071360460', 'IEMC8FWN5j', 0);
-- insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (28, 'Nikaniki', 'nlegallor', 'nlaylandr@biblegateway.com', '3542632387158495', '9vBMdqvoKz5', 1);
-- insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (29, 'Brewer', 'bgermons', 'brotterys@amazonaws.com', '3568059324493091', 'MO7gLV29Q', 1);
insert into CLIENTEENTITY (id, nombre, nombreUsuario, correoElectronico, identificacion, contrasenia, tipoCliente) values (30, 'Pietra', 'ppriddist', 'pnelmest@blog.com', '374622457259256', 'faTrYwUP', 0);

